apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    rule_files:
      - 'alert.rules'

    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager:9093"


    scrape_configs:
      - job_name: 'Prometheus'
        static_configs:
          - targets: ["localhost:9090"]
      - job_name: 'Flask'
        static_configs:
          - targets: ["flask-app-service:5000"]
      - job_name: 'Loki'
        static_configs:
          - targets: ["loki-service:3100"]
      - job_name: 'Node exporter'
        static_configs:
          - targets: ["node-exporter:9100"]

  alert.rules: |-
    groups: 
      - name: test
        rules:
        - alert: PrometheusTargetMissing
          expr: up == 0
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: "Prometheus target missing (instance {{ $labels.instance }})"
            description: "A Prometheus target has disappeared. An exporter might be crashed. VALUE = {{ $value }}  LABELS: {{ $labels }}"