apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    
    scrape_configs:
      - job_name: 'Prometheus'
        static_configs:
          - targets: ["localhost:9090"]
      - job_name: 'Flask'
        static_configs:
          - targets: ["flask-app-service:5000"]
      - job_name: 'Loki'
        static_configs:
          - targets: ["loki-service:3100"]
