---
# tasks file for jenkins

- name: Add jenkins apt key
  ansible.builtin.apt_key:
    url: "{{ jenkins_apt_key }}"
    state: present

- name: Add jenkins repo
  ansible.builtin.apt_repository:
    repo: "{{ jenkins_repo }}"
    state: present

- name: Update apt cache 
  ansible.builtin.apt:
    update_cache: true
    state: latest

- name: Install java
  ansible.builtin.apt:
    name: "{{ java_version }}"
    state: present

- name: Install jenkins
  ansible.builtin.apt:
    name: jenkins
    state: latest

  notify: Start jenkins

- name: Add user to jenkins group
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: jenkins
    append: true
    
  notify: Reload service