apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager
data:
  config.yml: |-
    global:
      
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 10s
      receiver: 'stardata-telegram'

    receivers:
    
      - name: 'stardata-telegram'
        telegram_configs:
        - bot_token: '<YOUR TOKEN>'
          api_url: https://api.telegram.org
          chat_id: YOUR ID
          message:  "Alertname: {{ .GroupLabels.alertname }}\n Severity: {{ .CommonLabels.severity }}\n {{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
          parse_mode: ''