apiVersion: v1
kind: Service
metadata:
  name: loki-service
  labels:
    app: loki
spec:
  selector:
    app: loki
  type: NodePort
  ports:
    - port: 3100
      targetPort: 3100
      protocol: TCP

