apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: promtail
  labels:
    app: promtail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: promtail 
      containers:
        - name: promtail
          image: grafana/promtail
          imagePullPolicy: Always
          args: ["-config.file=/etc/promtail/promtail-config.yaml"]
          volumeMounts:
          - name: promtail-config
            mountPath: /etc/promtail/
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
          - name: docker-sock
            mountPath: /var/run/docker.sock
          env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          resources:
            limits:
              memory: 256Mi
              cpu: "1"
            requests:
              memory: 128Mi
              cpu: "0.2"
      volumes:
        - name: promtail-config
          configMap:
            name: promtail-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
  