# Default values for flask.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  imagePullPolicy: Always
  repository: justhynd/flask-app-devops
  tag: monitoring 
  containerPort: 5000

service:
  name: flask-app-service
  type: ClusterIP
  port: 5000
  targetPort: 5000
  protocol: TCP

ingress:
  enabled: true
  className: public
  