pipeline {
    agent none
    stages {
        stage("Test configurations") {
            agent { label 'slave' }
            steps {
                sh 'ansible-lint ansible/'
            }
        }

        stage("Working with code") {
            agent { label 'slave' }
            steps {
                sh 'flake8 src/'
            }            
        }
    }
}
