pipeline {
    agent none

    environment {   
        REGESTRY_URL = "dockerregistry.local:5000"
        DOCKER_IMAGE_NAME = "flask-app-devops"
        TAG = "monitoring"
    }

    stages {
        

        stage("Test configurations") {
            agent { label 'slave' }
            steps {
                sh 'ansible-lint ansible/'
            }
        }

        stage("Working with code") {
            agent { label 'slave' }
            steps {
                sh 'flake8 src/'
            }     
        }

        stage('Build image') {
            agent { label 'master' }
            steps {
                script {
                    def version = readFile(file: '.build-version')
                    println(version)
                    sh "docker build -t ${REGESTRY_URL}/${DOCKER_IMAGE_NAME}:${TAG}-${version} src/"
                }
            }
        }
 
        stage('Push image') {
            agent { label 'master' }
            steps {
                script {
                    def version = readFile(file: '.build-version')
                    println(version)
                    sh "docker push ${REGESTRY_URL}/${DOCKER_IMAGE_NAME}:${TAG}-${version}"
                }
            }
        }

        stage('Update flask chart version') {
            agent { label 'master' } {
                script {
                    def version = readFile(file: '.build-version')
                    catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                        withCredentials([usernamePassword(credentialsId: 'github', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                            sh "git config user.email sasha_golovin_95@bk.ru"
                            sh "git config user.name Proxypepe"

                            sh "sed -i 's/monitoring.*/monitoring-${version}/' helm/flask/values.yaml"

                            sh "git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/${GIT_USERNAME}/final-project.git HEAD:main"

                        }
                    }
                }
            }
        }
    }
}
